spring:
  application:
    name: edgeserver
    
server:
  port: 6061
  
eureka:
  instance:
    ip-address: true
    lease-renewal-interval-in-seconds: 10
    metadata-map:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    service-url:
      default-zone: http://localhost:8760/eureka/
      
zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    authclientservice:
      path=/authclientservice/**
      serviceId=AUTHCLIENTSERVICE
  ribbon:
    restclient:
      enabled=true
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds=60000      
  
  
