spring:
  application:
    name: config-service 
  cloud:
    config:
     server:
      git:
       uri: https://github.com/ketan-gote/config
                
                
server:
  port: 8081
     